---
- hosts: all
  become: yes
  vars:
    - jenkins_repo_key_url: http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key
    - jenkins_repo_url: deb http://pkg.jenkins.io/debian-stable binary/

  tasks:
    - name: install jenkins repo keys
      apt_key:
        url: "{{ jenkins_repo_key_url }}"
        state: present

    - name: create apt repo
      apt_repository:
        repo: "{{ jenkins_repo_url }}"
        update_cache: yes
        state: present

    - name: update apt cache
      apt:
        pkg: jenkins
        state: present

    - name: start jenkins service
      service: name=jenkins state=started
