---
- name: download update-center.json
  get_url:
    url: "{{ jenkins_update_center_json_url }}"
    dest: /tmp/update-center.json
  become_user: jenkins

- name: get the content of update-center.json
  shell: "cat /tmp/update-center.json | sed '1d;$d'"
  register: content

- name: post update-center.json to jenkins
  shell: "curl -X POST --user {{ jenkins_admin_user }}:{{ jenkins_admin_password }} --data /tmp/update-center.json http://{{ jenkins_hostname }}:{{ jenkins_http_port }}/updateCenter/byId/default/postBack"
#   uri:
#     url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}/updateCenter/byId/default/postBack"
#     user: "{{ jenkins_admin_user }}"
#     password: "{{ jenkins_admin_password }}"
#     body: "{{ content.stdout }}"
#     force_basic_auth: yes
#     headers:
#       Accept: application/json
#     method: POST
