---
- name: install jenkins
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - jenkins
    - git
    - gcc-c++
    - ruby-devel
    - make
    - autoconf
    - automake
    - rubygems
