---
- name: install jenkins package dependencies
  apt:
    pkg:
      - git
      - gcc
      - ruby-dev
      - make
      - autoconf
      - automake
      - rubygems
      - openjdk-8-jdk
    state: present

- name: download jenkins package {{ jenkins_pkg_version }}
  get_url:
    url: "{{ jenkins_pkg_url }}/binary/jenkins_{{jenkins_pkg_version}}_all.deb"
    dest: /tmp/jenkins_{{jenkins_pkg_version}}_all.deb

- name: install jenkins {{ jenkins_pkg_version }}
  apt:
    deb: /tmp/jenkins_{{jenkins_pkg_version}}_all.deb
    state: present

- name: enable ufw
  ufw:
    state: enabled
    port: 8080
    policy: allow
