---
- name: download jenkins-cli
  command: >
    curl http://127.0.0.1:8080/jnlpJars/jenkins-cli.jar -o /bin/jenkins-cli.jar
  args:
    creates: /bin/jenkins-cli.jar

- name: setup permissions
  file:
    path: /bin/jenkins-cli.jar
    owner: root
    group: root
    mode: "0755"

- name: create jenkins-cli password file
  copy:
    content: "{{ jenkins_admin_password }}"
    dest: /opt/jenkins/jenkins-password.txt
    owner: jenkins
    group: jenkins
    mode: "0600"

- name: deploy jenkins-cli shell script
  template:
    src: jenkins-cli.j2
    dest: /bin/jenkins-cli
    owner: root
    group: root
    mode: "0755"

# this block handle scm-sync-configure repo
- block:
  - pip:
      name: pexpect
      state: present

  - file:
      path: "{{ jenkins_home }}/.config"
      state: directory
      owner: jenkins
      group: jenkins
      mode: "0755"

  - template:
      src: hub.config.j2
      dest: "{{ jenkins_home }}/.config/hub"
      owner: jenkins
      group: jenkins
      mode: "0644"

  - command: git init "{{ jenkins_home }}/scm-sync-configuration/checkoutConfiguration"
    changed_when: false
    become_user: jenkins

  - command: hub config --global hub.protocol https
    changed_when: false
    become_user: jenkins

  - command: git add .
    args:
      chdir: "{{ jenkins_home }}/scm-sync-configuration/checkoutConfiguration"
    become_user: jenkins
    changed_when: false

  - command: git commit -m 'initial jenkins configuration checkin'
    args:
      chdir: "{{ jenkins_home }}/scm-sync-configuration/checkoutConfiguration"
    become_user: jenkins
    changed_when: false

  - command: /usr/local/bin/hub create {{ jenkins_github_repo }}
    args:
      chdir: "{{ jenkins_home }}/scm-sync-configuration/checkoutConfiguration"
    become_user: jenkins
    changed_when: false

  - expect:
      command: hub push -u --all origin
      responses:
        'Username.*:': wilddog64
        'Password.*:': "{{ jenkins_github_api_token }}"
      chdir: "{{ jenkins_home }}/scm-sync-configuration/checkoutConfiguration"
    changed_when: false
    become_user: jenkins
