---
- name: get jenkins package
  get_url:
    url: "{{ jenkins_pkg_url }}/jenkins-{{ jenkins_pkg_version }}-1.1.noarch.rpm"
    dest: /tmp/jenkins-{{ jenkins_pkg_version }}-1.1.noarch.rpm

- block: # to handle jenkins upgrade and downgrade
  - name: install jenkins {{ jenkins_pkg_version }}
    yum:
      name: /tmp/jenkins-{{ jenkins_pkg_version }}-1.1.noarch.rpm
      state: present
    register: package_state

  rescue:
  - name: remove previous installed jenkins
    yum:
      name: jenkins
      state: absent
    when: "'Nothing to do' in package_state.msg"

  - name: now install different version of jenkins
    yum:
      name: /tmp/jenkins-{{ jenkins_pkg_version }}-1.1.noarch.rpm
      state: present

- name: install packages
  yum:
    pkg:
      - git
      - gcc-c++
      - ruby-devel
      - make
      - autoconf
      - automake
      - rubygems
      - nmap-ncat
    state: present

- name: enable firewalld
  service: name=firewalld state=started enabled=yes

- name: allow port {{ jenkins_http_port }} traffice
  firewalld:
    port: "{{ jenkins_http_port }}/tcp"
    permanent: true
    state: enabled
