---
- name: get jenkins package
  get_url:
    url: "{{ jenkins_pkg_url }}/jenkins-{{ jenkins_pkg_version }}.noarch.rpm"
    dest: /tmp/jenkins-{{ jenkins_pkg_version }}.noarch.rpm

- name: install jenkins
  yum:
    name: "/tmp/jenkins-{{ jenkins_pkg_version }}.noarch.rpm"
    state: present

- name: install jenkins
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - git
    - gcc-c++
    - ruby-devel
    - make
    - autoconf
    - automake
    - rubygems
    - nmap-ncat

- name: enable firewalld
  service: name=firewalld state=started enabled=yes

- name: allow port {{ jenkins_http_port }} traffice
  firewalld:
    port: "{{ jenkins_http_port }}/tcp"
    permanent: true
    state: enabled
