---
- name: install jenkins
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - jenkins
    - git
    - gcc-4.7
    - ruby-dev
    - make
    - autoconf
    - automake
    - rubygems
