---
- name: get jenkins package
  get_url:
    url: "{{ jenkins_pkg_url }}/jenkins-{{ jenkins_pkg_version }}.noarch.rpm"
    dest: /tmp/jenkins-{{ jenkins_pkg_version }}-1.1.noarch.rpm

- name: get current installed jenkins on the system
  shell: >
    rpm -qa jenkins
  ignore_errors: yes
  register: current_jenkins

- name: get jenkins version from an installed package
  shell: echo {{ current_jenkins.stdout }} | perl -nle 'print $1 if /-(.*)-/'
  ignore_errors: yes
  register: jenkins_version

- name: uninstall current jekins
  yum:
    name: "{{ current_jenkins.stdout }}"
    state: absent
  when: |
    jenkins_pkg_version | version_compare(jenkins_version.stdout, '<')

- name: install jenkins
  yum:
    name: "/tmp/jenkins-{{ jenkins_pkg_version }}-1.1.noarch.rpm"
    state: present

- name: install packages
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - git
    - gcc-c++
    - ruby-devel
    - make
    - autoconf
    - automake
    - rubygems
    - nmap-ncat

- name: enable firewalld
  service: name=firewalld state=started enabled=yes

- name: allow port {{ jenkins_http_port }} traffice
  firewalld:
    port: "{{ jenkins_http_port }}/tcp"
    permanent: true
    state: enabled
