---
- name: collect facts
  setup:

- include_vars: "{{ ansible_os_family }}.yml"
- include: "tasks/setup.{{ ansible_os_family }}.repo.yml"
- include: "tasks/install.{{ ansible_os_family }}.jenkins.yml"
- include: "tasks/settings.yml"
- include: "tasks/start.jenkins.service.yml"
