---
- name: collect facts
  setup:

- include_vars: "{{ ansible_os_family }}.yml"
- name: install python-pip
  include_role:
    name: install-python-pip

- include: "tasks/setup.{{ ansible_os_family }}.repo.yml"
- include: "tasks/install.{{ ansible_os_family }}.jenkins.yml"
- include: "tasks/config-jenkins-selfsigned-ssl.yml"
  when: "{{ jenkins_enable_selfsigned_ssl }}"
- include: "tasks/settings.yml"
- include: "tasks/manage_github.yml"
  when: "{{ jenkins_enable_github_repo }}"
- include: "tasks/start.jenkins.service.yml"
- include: "tasks/install-config-jenkins.yml"
