---
tasks:
  - name: Jenkins | install jenkins repo keys
    apt_key:
      url: "{{ jenkins_repo_key_url }}"
      state: present

  - name: Jenkins | create apt repo
    apt_repository:
      repo: "{{ jenkins_repo_url }}"
      update_cache: yes
      state: present

  - name: Jenkins | install jenkins
    apt:
      pkg: jenkins
      state: present

  - name: start jenkins service
    service: name=jenkins state=started
