---
- name: Jenkins | install jenkins repo keys
  apt_key:
    url: "{{ jenkins_repo_key_url }}"
    state: present

- name: Jenkins | create apt repo
  apt_repository:
    repo: "{{ jenkins_repo_url }}"
    update_cache: yes
    state: present

- name: Jenkins | install jenkins
  apt:
    pkg: jenkins
    state: installed

- name: Jenkins | remove initial Jenkins password
  file: name=/var/lib/jenkins/secrets/initialAdminPassword state=absent
  become_user: jenkins

- name: create Jenkins admin password hash
  command: echo -n {{ jenkins_admin_password }} | sha256sum - | awk '{ print $1; }'
  register: jenkins_password_hash
  become_user: jenkins
  retries: 3
  delay: 2

- name: Jenkins admin config.xml exists
  stat: path=/var/lib/jenkins/users/admin/config.xml
  until: st.stat.exists
  register: st

- name: Jenkins output admin config.xml stat
  debug: var=st

- name: Jenkins | supress wizard mode
  lineinfile:
    dest: /etc/default/jenkins
    insertbefore: ^JENKINS_ARGS.*
    line: "JAVA_ARGS={{ jenkins_java_args }}"
    state: absent
  become_user: jenkins

- name: Jenkins | patch original password hash line
  lineinfile:
    dest: /var/lib/jenkins/users/admin/config.xml
    regexp: '^(\s)*<passwordHash>(.*)'
    line: "      <passwordHash>ansible_jenkins:{{ jenkins_password_hash.stdout }}</passwordHash>"
    state: present
  when: st.stat.exists and jenkins_password_hash
  become_user: jenkins
  notify: restart Jenkins


# - name: Jenkins | grab Jenkins crumb
#   uri:
#     user: "{{ jenkins_admin_user }}"
#     password: "{{ jenkins_admin_password }}"
#     force_basic_auth: yes
#     return_content: yes
#   register: crumb_token
#   when: st.stat.exists
#   retries: 10
#   delay: 5

- name: debug jenkins crumb
  debug: var=crumb_token

  # - name: Jenkins | set crumb token
  #   set_fact:
  #     jenkins_crumb_token: "{{ crumb_token.json.crumbRequestField }}={{ crumb_token.json.crumb }}"
  #   when: crumb_token.changed

- name: Jenkins | start jenkins service
  service: name=jenkins state=started
  when: jenkins_password_hash
