---
- name: list ssh github public keys
  command: >
    curl -f -H 'Authorization: token {{ jenkins_github_api_token }}' https://api.github.com/user/keys
  register: curl_output
  changed_when: false

- name: set github keys fact
  set_fact:
    github_keys: "{{ curl_output.stdout }}"
    github_sshkey_name: "{{ ansible_hostname }}-{{ jenkins_git_commiter_name }}"

- name: get ssh public key
  command: >
    cat {{ jenkins_ssh_public_keyfile }}
  register: sshkey
  changed_when: false

- name: install pexpect
  pip:
    name: pexpect
    state: present

- name: upload jenkins ssh public key if it does not exist
  github_key:
    name: "{{ ansible_hostname }}-{{ jenkins_git_commiter_name }}"
    token: "{{ jenkins_github_api_token }}"
    pubkey: "{{ sshkey.stdout }}"
    state: present
  when: "{{ not github_keys | selectattr('title', 'equalto', github_sshkey_name) | list }}"

- name: copy ssh-add-key script
  copy:
    src: ../files/scripts/ssh-add-key.sh
    dest: /tmp/ssh-add-key.sh
    owner: jenkins
    group: jenkins
    mode: "0755"

- name: add ssh key to ssh agent
  expect:
    command: /tmp/ssh-add-key.sh
    responses:
      '.*passphrase.*:': "{{ sshkey_passphrase }}"
  become_user: jenkins
  changed_when: false
