---
- name: upload ssh public key to github
  command: >
    curl -f -H 'Authorization: token {{ jenkins_github_api_token }}' https://api.github.com/user/keys
  register: curl_output
  changed_when: false

- name: set github keys fact
  set_fact:
    github_keys: "{{ curl_output.stdout }}"

- name: get ssh public key
  command: >
    cat {{ jenkins_ssh_public_keyfile }}
  register: sshkey
  changed_when: false

- name: upload ssh jenkins ssh public key if it does not exist
  command: >
    curl -i -f -H 'Authorization: token {{ jenkins_github_api_token }}' https://api.github.com/user/keys
      -H 'Content-Type: application/json'
      -H 'Accept: application/json' 
      -d '{ "title": "{{ jenkins_git_commiter_name }}", "key": "{{ sshkey.stdout }}" }'
  when: "{{not github_keys | selectattr('title', 'equalto', jenkins_git_commiter_name) | list }}"
