---
- name: set jenkins home directory
  lineinfile:
    dest: "{{ jenkins_init_file }}"
    regexp: '^JENKINS_HOME.*'
    line: 'JENKINS_HOME={{ jenkins_home }}'
  register: jenkins_home_config

- name: set http port in jenkins config
  lineinfile:
    backrefs: yes
    dest: "{{ jenkins_init_file }}"
    regexp: '^{{ jenkins_http_port }}'
    line: 'JENKINS_PORT={{ jenkins_http_port }}'
  register: jenkins_http_config

- name: supress wizard mode
  lineinfile:
    dest: "{{ jenkins_init_file }}"
    insertbefore: "^JENKINS_ARGS.*"
    line: "JAVA_ARGS=\"{{ jenkins_java_args }}\""
  register: jenkins_supress_wizard

- name: deploy shell scripts for install jenkins plugins
  template:
    src: install_jenkins_plugin.sh.j2
    dest: "{{ jenkins_home }}/install_jenkins_plugin.sh"
    owner: jenkins
    group: jenkins
    mode: "0755"

- name: install minimum plugins for jenkins
  shell: >
    {{ jenkins_home }}/install_jenkins_plugin.sh {{ item }}
  args:
    creates: "{{ jenkins_home }}/plugins/{{ item }}"
  register: install_plugins
  with_items: "{{ jenkins_default_plugins }}"

# immediately restart jenkins so plugins are loaded
- name: restart jenkins for plugins to load
  service:
    name: jenkins
    state: restarted
  when: install_plugins.changed

- name: create custom jenkin init scripts directory
  file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0775
  register: jenkins_init_directory_created
  # notify: configure default users

- name: create jenkins_sshkey_file fact
  set_fact:
    jenkins_sshkey_file: "/root/.ssh/id_rsa"
    jenkins_ssh_public_keyfile: "/root/.ssh/id_rsa.pub"

- name: configure default users
  template:
    src: basic-security.groovy.j2
    dest: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
  register: jenkins_init_config
  when: jenkins_init_directory_created.changed

- name: manage jenkins ssh keys
  user:
    name: root
    createhome: no
    generate_ssh_key: yes
    group: jenkins
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    ssh_key_passphrase: "{{ sshkey_passphrase }}"
