---
- name: set jenkins home directory
  lineinfile:
    dest: "{{ jenkins_init_file }}"
    regexp: '^JENKINS_HOME.*'
    line: 'JENKINS_HOME={{ jenkins_home }}'
  register: jenkins_home_config

- name: set http port in jenkins config
  lineinfile:
    backrefs: yes
    dest: "{{ jenkins_init_file }}"
    regexp: '^{{ jenkins_http_port }}'
    line: 'JENKINS_PORT={{ jenkins_http_port }}'
  register: jenkins_http_config

- name: supress wizard mode
  lineinfile:
    dest: "{{ jenkins_init_file }}"
    insertbefore: "^JENKINS_ARGS.*"
    line: "JAVA_ARGS=\"{{ jenkins_java_args }}\""
  register: jenkins_supress_wizard

- name: create custom jenkin init scripts directory
  file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0775
  register: directory_created
  # notify: configure default users

- name: configure default users
  template:
    src: basic-security.groovy
    dest: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
  when: directory_created.changed
