---
- name: install jenkins repo keys
  apt_key:
    url: "{{ jenkins_repo_key_url }}"
    state: present

- name: create apt repo
  apt_repository:
    repo: "{{ jenkins_repo_url }}"
    update_cache: yes
    state: present

