---
- name: remove initial Jenkins password
  file:
    path: "{{ jenkins_home }}/secrets/initialAdminPassword"
    state: absent
  register: jenkins_remove_init_admin_password

- name: start jenkins service
  service: name=jenkins state=restarted
  when: (jenkins_users_config is defined and jenkins_users_config.changed) or
        (jenkins_http_config is defined and jenkins_http_config.changed) or
        (jenkins_home_config is defined and jenkins_home_config.changed) or
        (jenkins_supress_wizard is defined and jenkins_supress_wizard.changed) or
        (jenkins_remove_init_admin_password and jenkins_remove_init_admin_password.changed) or
        (jenkins_init_config is defined and jenkins_init_config.changed) 

- name: Wait for Jenkins to start up before proceeding.
  wait_for:
    host: "localhost.{{ local_domain }}"
    port: "{{ jenkins_http_port }}"
    state: started
    delay: 60
  delegate_to: 127.0.0.1
  become: no
