---
- name: Jenkins | start jenkins service
  service: name=jenkins state=started
  # when: jenkins_password_hash

- name: Wait for Jenkins to start up before proceeding.
  wait_for: 
    host: "{{ jenkins_hostname }}"
    port: "{{ jenkins_http_port }}"
