---
- name: start jenkins service
  service: name=jenkins state=restarted
  when: (jenkins_users_config is defined and jenkins_users_config.changed) or
        (jenkins_http_config is defined and jenkins_http_config.changed) or
        (jenkins_home_config is defined and jenkins_home_config.changed) or
        (jenkins_supress_wizard is defined and jenkins_supress_wizard.changed)

- name: Wait for Jenkins to start up before proceeding.
  wait_for:
    host: "{{ jenkins_hostname }}"
    port: "{{ jenkins_http_port }}"
    state: started

- name: remove Jenkins security init scripts after first startup
  file:
    path: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
    state: absent

- name: remove initial Jenkins password
  command: bash -c [[ test -e "{{ jenkins_home }}/secrets/initialAdminPassword" ]] && rm -rf "{{ jenkins_home }}/secrets/initialAdminPassword"
