---
- name: remove initial Jenkins password
  file:
    path: "{{ jenkins_home }}/secrets/initialAdminPassword"
    state: absent
  register: jenkins_remove_init_admin_password

- name: start jenkins service
  service: name=jenkins state=restarted
  when: (jenkins_users_config is defined and jenkins_users_config.changed) or
        (jenkins_http_config is defined and jenkins_http_config.changed) or
        (jenkins_home_config is defined and jenkins_home_config.changed) or
        (jenkins_supress_wizard is defined and jenkins_supress_wizard.changed) or
        (jenkins_remove_init_admin_password and jenkins_remove_init_admin_password.changed) or
        (jenkins_init_config is defined and jenkins_init_config.changed) 

- name: Wait for Jenkins to start up before proceeding.
  wait_for:
    host: "{{ jenkins_hostname }}"
    port: "{{ jenkins_http_port }}"
    state: started
    delay: 15

- name: download jenkins-cli
  command: >
    curl http://127.0.0.1:8080/jnlpJars/jenkins-cli.jar -o /opt/jenkins/jenkins-cli.jar
  args:
    creates: /opt/jenkins/jenkins-cli.jar

- name: setup permissions
  file:
    path: /opt/jenkins/jenkins-cli.jar
    owner: root
    group: root
    mode: "0755"

